<?php

/** Generated by Latte 3.1.3 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: folder/hello.latte */
final class Template_f35d1c0ce7 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo 'Hello, ';
		echo LR\HtmlHelpers::escapeText($name) /* pos 1:8 */;
		echo '!';
	}
}
