<?php

/** Generated by Latte 3.1.3 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: folder/bye.latte */
final class Template_299ae961f4 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo 'Bye, ';
		echo LR\HtmlHelpers::escapeText($name) /* pos 1:6 */;
		echo '!';
	}
}
